instrument_keywords = {
    "Piano": "piano",
    "BrightPiano": "bright piano",
    "ElectricPiano1": "epiano1",
    "ElectricPiano2": "epiano2",
    "Harpsichord": "harpsichord",
    "Celesta": "celesta",
    "Glockenspiel": "glockenspiel",
    "MusicBox": "music box",
    "Vibraphone": "vibraphone",
    "Marimba": "marimba",
    "Xylophone": "xylophone",
    "TubularBells": "tubular bells",
    "Dulcimer": "dulcimer",
    "DrawbarOrgan": "organ drawbar",
    "PercussiveOrgan": "organ perc",
    "RockOrgan": "organ rock",
    "ChurchOrgan": "organ church",
    "ReedOrgan": "reed organ",
    "Accordion": "accordion",
    "Harmonica": "harmonica",
    "Bandoneon": "bandoneon",
    "GuitarNylon": "guitar nylon",
    "GuitarSteel": "guitar steel",
    "GuitarJazz": "guitar jazz",
    "GuitarClean": "guitar clean",
    "GuitarMute": "guitar mute",
    "Guitar":"acoustic guitar",
    "GuitarOverdrive": "guitar overdrive",
    "GuitarDistortion": "guitar distortion",
    "GuitarHarmonics": "guitar harmonics",
    "BassAcoustic": "bass acoustic",
    "BassFinger": "bass finger",
    "BassPick": "bass pick",
    "BassFretless": "bass fretless",
    "BassSlap1": "bass slap1",
    "BassSlap2": "bass slap2",
    "BassSynth1": "bass synth1",
    "BassSynth2": "bass synth2",
    "Violin": "violin",
    "Viola": "viola",
    "Cello": "cello",
    "Contrabass": "contrabass",
    "StringsTremolo": "strings tremolo",
    "StringsPizzicato": "strings pizzicato",
    "Harp": "harp",
    "Timpani": "timpani",
    "Strings1": "strings 1",
    "Strings2": "strings 2",
    "SynthStrings1": "strings synth1",
    "SynthStrings2": "strings synth2",
    "ChoirAahs": "choir aahs",
    "VoiceOohs": "voice oohs",
    "SynthVoice": "voice synth",
    "Trumpet": "trumpet",
    "Trombone": "trombone",
    "Tuba": "tuba",
    "MuteTrumpet": "trumpet mute",
    "FrenchHorn": "french horn",
    "Brass": "brass",
    "SynthBrass1": "brass synth1",
    "SynthBrass2": "brass synth2",
    "SopranoSax": "sax soprano",
    "AltoSax": "sax alto",
    "TenorSax": "sax tenor",
    "BaritoneSax": "sax baritone",
    "Oboe": "oboe",
    "EnglishHorn": "english horn",
    "Bassoon": "bassoon",
    "Clarinet": "clarinet",
    "Piccolo": "piccolo",
    "Flute": "flute",
    "Recorder": "recorder",
    "PanFlute": "pan flute",
    "BottleChiff": "bottle chiff",
    "Shakuhachi": "shakuhachi",
    "Whistle": "whistle",
    "Ocarina": "ocarina"
}
